// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApC_xyM_nGSCAkK6_WTqbHasP8SYvWD34',
    appId: '1:426972970503:web:2ca7a156a520ec065134a2',
    messagingSenderId: '426972970503',
    projectId: 'login-7a56f',
    authDomain: 'login-7a56f.firebaseapp.com',
    storageBucket: 'login-7a56f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYsJ9RQOJ84ZNpFYIinFcCxIGnE0Stqc',
    appId: '1:426972970503:android:dc8a4992732c525c5134a2',
    messagingSenderId: '426972970503',
    projectId: 'login-7a56f',
    storageBucket: 'login-7a56f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiUo4UjqRa5qRswFwQB5xvbyCDmsIBtI',
    appId: '1:426972970503:ios:74c5992b31edb6025134a2',
    messagingSenderId: '426972970503',
    projectId: 'login-7a56f',
    storageBucket: 'login-7a56f.appspot.com',
    iosClientId: '426972970503-6a8s81kt1ocmu0n3bpds35jq7ei3eba0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiUo4UjqRa5qRswFwQB5xvbyCDmsIBtI',
    appId: '1:426972970503:ios:74c5992b31edb6025134a2',
    messagingSenderId: '426972970503',
    projectId: 'login-7a56f',
    storageBucket: 'login-7a56f.appspot.com',
    iosClientId: '426972970503-6a8s81kt1ocmu0n3bpds35jq7ei3eba0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui3',
  );
}
